FROM golang:1.21-alpine as go-builder
WORKDIR /app
COPY . .
RUN go build -o ./serviceA ./cmd/serviceA/main.go

FROM alpine:3.19
WORKDIR /app
COPY --from=go-builder /app/serviceA .
CMD [ "./serviceA" ]